<script lang="ts">
	/**
	 * The OpusTags comment header, printed the way ffprobe prints it.
	 * Values come from src/lib/generated/demo.json, which is generated by
	 * scripts/gen-demo.mjs from the .opus file this page links to.
	 */
	type Row = { key: string; value: string; kind: 'std' | 'desc' | 'chunk' | 'sum' };

	let {
		rows,
		title = 'meeting.opus',
		command = '',
		note = '',
		max = 0,
		count = 0
	}: {
		rows: Row[];
		title?: string;
		command?: string;
		note?: string;
		max?: number;
		count?: number;
	} = $props();

	// DECODE_HINT is a whole sentence and would push the block sideways.
	const clamp = (value: string) => (value.length > 96 ? value.slice(0, 96) + '…' : value);

	let expanded = $state(false);
	const shown = $derived(max && !expanded ? rows.slice(0, max) : rows);
	const hidden = $derived(max && !expanded ? rows.length - max : 0);
</script>

<div class="dump">
	<div class="code__bar">
		<span>{title}</span>
		<span class="count">{count || rows.length} comments</span>
	</div>
	{#if command}
		<div class="cmd"><span class="prompt">$</span> {command}</div>
	{/if}
	<div class="rows">
		{#each shown as row (row.key)}
			<div class="row" data-kind={row.kind}>
				<span class="k">{row.key}</span><span class="eq">=</span><span class="v"
					>{clamp(row.value)}</span
				>
			</div>
		{/each}
		{#if hidden > 0}
			<button class="more" type="button" onclick={() => (expanded = true)}>
				+ {hidden} more
			</button>
		{/if}
	</div>
	{#if note}
		<p class="note">{note}</p>
	{/if}
</div>

<style>
	.dump {
		font-family: var(--mono);
		border: 1px solid var(--rule);
		background: var(--bg-raise);
		font-size: 12.5px;
		line-height: 1.75;
		overflow: hidden;
	}
	.count {
		color: var(--fg-5);
	}
	.cmd {
		padding: 0.7rem 1rem 0.2rem;
		color: var(--fg-2);
		white-space: pre-wrap;
		word-break: break-word;
	}
	.prompt {
		color: var(--blue);
		user-select: none;
		margin-right: 0.4rem;
	}
	.rows {
		padding: 0.55rem 1rem 0.9rem;
		overflow-x: auto;
	}
	.row {
		white-space: pre;
	}
	.k {
		color: var(--fg-3);
	}
	.eq {
		color: var(--fg-5);
	}
	.v {
		color: var(--fg);
	}
	/* The two descriptor tags that explain the whole format get the accent. */
	.row[data-kind='desc'] .k {
		color: var(--blue);
	}
	.row[data-kind='desc'] .v {
		color: var(--blue);
	}
	.row[data-kind='chunk'] .v {
		color: var(--fg-4);
	}
	.row[data-kind='std'] .k {
		color: var(--amber);
	}
	.more {
		font: inherit;
		margin-top: 0.5rem;
		background: none;
		border: 0;
		border-bottom: 1px dashed var(--rule-hi);
		color: var(--fg-4);
		cursor: pointer;
		padding: 0 0 1px;
	}
	.more:hover {
		color: var(--fg);
	}
	.note {
		margin: 0;
		padding: 0.7rem 1rem;
		border-top: 1px solid var(--rule);
		color: var(--fg-4);
		font-size: 12px;
		max-width: none;
	}
</style>
